### ISSUE TITLE
Fix 404 links with aliases

### ISSUE THREAD

**Issue by kinow** [kinow/kinoshita.eti.br#220]
Programmatically iterate blog posts older than the Jekyll → Hugo migration, and add an alias, to fix the old links (e.g. Hacker News).

e.g.

```yaml
(…)
title: Jenkins, TestLink and GTest in 5 minutes (or so)
aliases:
  - "/2012/10/11/jenkins-testlink-and-gtest-in-5-minutes-or-so/index.html"
  - "/2012/10/11/jenkins-testlink-and-gtest-in-5-minutes-or-so.html"
---
```
