### ISSUE TITLE
post: filtros do r/chaves

### ISSUE THREAD

**Issue by kinow** [kinow/kinoshita.eti.br#223]
Até para não esquecer:

```yaml
---
# Filters content without title
title+body (regex, case-sensitive):
 - '^\s*[.\s]*\s*$' # Wrapped by optional spaces, and contains only dots or spaces

action: remove
action_reason: "Por favor informe um titulo para o seu post"
---

---
# Filters content with too many uppercase words
title+body (regex, case-sensitive):
 - '^(?!.*?[a-z])(?=.*?\b(\w+\b\W*){3})' # field doesn't contain a lowercase letter but contains at least 3 words
 - '([A-Z]{2,}\b\W*(\b[A-Z]\W+)?){3}' # field contains at least 3 uppercase words (2+ letters) together (with optional 1 letter words inbetween)
 - '([A-Z]{2,}\b.*?){2}' # field contains at least 2 uppercase words (2+ letters) anywhere

action: remove
action_reason: "Muitas maiusculas no texto, evite CHAVES, use Chaves"
---

---
author:
    post_karma: '< 100'
    comment_karma: '< 100'


action: remove
action_reason: "Usuario com karma abaixo do minimo para poder postar no subreddit"
---

---
# Filters banned domains
type: submission
domain+url (regex):     
   - twitter\.com
   - x\.com
action: remove
action_reason: Post removido - Link {{match-1}} detectado
message: |-
  Seu {{kind}} para /r/{{subreddit}} foi removido automaticamente pelo domínio do site enviado ter sido banido **{{match}}**.
---

---
title+body (includes, regex): ['(?i)\bchapolin\b', '(?i)\bchapolim\b']
action: remove
action_reason: Post removido por incluir palavras-chave como {{match}}
message: |-
  Se {{kind}} possui a palavra-chave {{match}}, e será moderado para verificar se o conteúdo é sobre Chaves (use r/chapolin para conteúdo do Chapolin).
---

E link dos docs: https://www.reddit.com/r/reddit.com/wiki/automoderator/full-documentation/
E de algo util: https://www.reddit.com/r/ModSupport/comments/1c5lfp2/how_to_make_an_automod_filter_for_specific_words/
```
